name: Haskell CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.2'
        stack-version: '2.7.5'

    - name: Cache
      uses: |
        - .stack
        - .stack-work
        - target


    - name: Install dependencies
      run: |
        stack update
        stack build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: stack exec math-exe
    - name: Run tests
      run: stack test
